<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Trans_detail extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Trans_detail_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('kasir/kasir1/trans_detail_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Trans_detail_model->json();
    }

    public function read($id) 
    {
        $row = $this->Trans_detail_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_trans' => $row->id_trans,
		'notrans' => $row->notrans,
		'kode_barang' => $row->kode_barang,
		'kode_m_kasir' => $row->kode_m_kasir,
		'qty' => $row->qty,
		'harga' => $row->harga,
		'jumlah' => $row->jumlah,
		'datetime' => $row->datetime,
	    );
            $this->template->load('template','trans_detail/trans_detail_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('trans_detail'));
        }
    }

}

/* End of file Trans_detail.php */
/* Location: ./application/controllers/Trans_detail.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-13 14:18:36 */
/* http://harviacode.com */