<?php

if (!defined('BASEPATH')) {
 exit('No direct script access allowed');
}

class Welcome extends CI_Controller
{

 public function __construct()
 {
  parent::__construct();
  $this->load->model('Trans_model');
  $this->load->library('form_validation');
  $this->session->set_flashdata('title', 'Dashboard | CV PUJI');
  $this->load->library('datatables');
 }

 public function index()
 {
  //$this->load->view('kasir/kasir1/trans_list', $data);
  $this->template->load('template', 'welcome');
 }

 public function ajax_list()
 {
  $list = $this->Trans_model->get_datatables();
  $data = array();
  $no   = $_POST['start'];
  foreach ($list as $customers) {
   $no++;
   $row   = array();
   $row[] = $no;
   $row[] = $customers->nama;
   $row[] = number_format($customers->jumlah);
   $row[] = $customers->datetime;
   $row[] = '<a class="btn btn-sm btn-primary" href="' . base_url('welcome/read/' . $customers->notrans) . '" title="Edit" target="_blank">Detail</a>';

   $data[] = $row;
  }

  $output = array(
   "draw"            => $_POST['draw'],
   "recordsTotal"    => $this->Trans_model->count_all(),
   "recordsFiltered" => $this->Trans_model->count_filtered(),
   "data"            => $data,
  );
  //output to json format
  echo json_encode($output);
 }

 public function read($notrans)
 {
  $data = array('notrans' => $notrans);
  //$this->load->view('kasir/kasir1/trans_read', $data);
  $this->template->load('template', 'trans_read', $data);

 }

}

/* End of file Absen.php */
/* Location: ./application/controllers/Absen.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-13 05:14:02 */
/* http://harviacode.com */
