<?php

if (!defined('BASEPATH')) {
 exit('No direct script access allowed');
}

class Agen_stock_model extends CI_Model
{

 public $table = 'stock_m_agen';
 public $id    = 'id';
 public $order = 'DESC';

 public function __construct()
 {
  parent::__construct();
 }

 // datatables
 public function json()
 {

  $this->datatables->select('stock_m_agen.kode_m_kasir,tab_barang.nama, stock_m_agen.kode_barang, stock_m_agen.stok');
  $this->datatables->from('stock_m_agen');
//   $this->datatables->where('stock_m_kasir.kode_m_kasir',$kode_m_kasir);
  $this->datatables->where('stock_m_agen.stok <>', 0);
  //add this line for join
  $this->datatables->join('tab_barang', 'stock_m_agen.kode_barang = tab_barang.kode_barang');
//   $this->datatables->add_column('action', anchor(site_url('stock_m_kasir/read/$1'), '<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . "
//             " . anchor(site_url('stock_m_kasir/update/$1'), '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . "
//                 " . anchor(site_url('stock_m_kasir/delete/$1'), '<i class="fa fa-trash-o" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
  return $this->datatables->generate();
 }

 // get all
 public function get_all()
 {
  $this->db->order_by($this->id, $this->order);
  return $this->db->get($this->table)->result();
 }

 // get data by id
 public function get_by_id($id)
 {
  $this->db->where($this->id, $id);
  return $this->db->get($this->table)->row();
 }

 // get total rows
 public function total_rows($q = null)
 {
  $this->db->like('id', $q);
  $this->db->or_like('kode_m_kasir', $q);
  $this->db->or_like('kode_barang', $q);
  $this->db->or_like('stok', $q);
  $this->db->or_like('datetime', $q);
  $this->db->from($this->table);
  return $this->db->count_all_results();
 }

 // get data with limit and search
 public function get_limit_data($limit, $start = 0, $q = null)
 {
  $this->db->order_by($this->id, $this->order);
  $this->db->like('id', $q);
  $this->db->or_like('kode_m_kasir', $q);
  $this->db->or_like('kode_barang', $q);
  $this->db->or_like('stok', $q);
  $this->db->or_like('datetime', $q);
  $this->db->limit($limit, $start);
  return $this->db->get($this->table)->result();
 }

 // insert data
 public function insert($data)
 {
  $this->db->insert($this->table, $data);
 }

 // update data
 public function update($id, $data)
 {
  $this->db->where($this->id, $id);
  $this->db->update($this->table, $data);
 }

 // delete data
 public function delete($id)
 {
  $this->db->where($this->id, $id);
  $this->db->delete($this->table);
 }

}

/* End of file Agen_stock_model.php */
/* Location: ./application/models/Agen_stock_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-13 04:30:24 */
/* http://harviacode.com */
