<?php

if (!defined('BASEPATH')) {
 exit('No direct script access allowed');
}

class Tab_barang_model extends CI_Model
{

 public $table = 'tab_barang';
 public $id    = 'kode_barang';
 public $order = 'DESC';

 public function __construct()
 {
  parent::__construct();
 }

 // datatables
 public function json()
 {
  $this->datatables->select('master_group.kode_group,master_group.nama_group,tab_barang.kode_barang,tab_barang.kode_group,tab_barang.barcode,tab_barang.nama,tab_barang.ukuran,tab_barang.merk,tab_barang.gambar,tab_barang.harga,tab_barang.harga_kasir,tab_barang.stok,tab_barang.keterangan,tab_barang.opsi2,tab_barang.opsi3,tab_barang.opsi4,tab_barang.opsi5');
  $this->datatables->from('tab_barang');
  //add this line for join
  $this->datatables->join('master_group', 'tab_barang.kode_group = master_group.kode_group');
  $this->datatables->add_column('action', anchor(site_url('tab_barang/read/$1'), '<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . "
            " . anchor(site_url('tab_barang/update/$1'), '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . "
                " . anchor(site_url('tab_barang/delete/$1'), '<i class="fa fa-trash-o" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'kode_barang');
  return $this->datatables->generate();
 }

 // get all
 public function get_all()
 {
  $this->db->order_by($this->id, $this->order);
  return $this->db->get($this->table)->result();
 }

 // get data by id
 public function get_by_id($id)
 {
  $this->db->where($this->id, $id);
  return $this->db->get($this->table)->row();
 }

 // get total rows
 public function total_rows($q = null)
 {
  $this->db->like('kode_barang', $q);
  $this->db->or_like('kode_group', $q);
  $this->db->or_like('nama', $q);
  $this->db->or_like('ukuran', $q);
  $this->db->or_like('merk', $q);
  $this->db->or_like('gambar', $q);
  $this->db->or_like('harga', $q);
  $this->db->or_like('stok', $q);
  $this->db->or_like('keterangan', $q);
  $this->db->or_like('opsi1', $q);
  $this->db->or_like('opsi2', $q);
  $this->db->or_like('opsi3', $q);
  $this->db->or_like('opsi4', $q);
  $this->db->or_like('opsi5', $q);
  $this->db->from($this->table);
  return $this->db->count_all_results();
 }

 // get data with limit and search
 public function get_limit_data($limit, $start = 0, $q = null)
 {
  $this->db->order_by($this->id, $this->order);
  $this->db->like('kode_barang', $q);
  $this->db->or_like('kode_group', $q);
  $this->db->or_like('nama', $q);
  $this->db->or_like('ukuran', $q);
  $this->db->or_like('merk', $q);
  $this->db->or_like('gambar', $q);
  $this->db->or_like('harga', $q);
  $this->db->or_like('stok', $q);
  $this->db->or_like('keterangan', $q);
  $this->db->or_like('opsi1', $q);
  $this->db->or_like('opsi2', $q);
  $this->db->or_like('opsi3', $q);
  $this->db->or_like('opsi4', $q);
  $this->db->or_like('opsi5', $q);
  $this->db->limit($limit, $start);
  return $this->db->get($this->table)->result();
 }

 // insert data
 public function insert($data)
 {
  $this->db->insert($this->table, $data);
 }

 // update data
 public function update($id, $data)
 {
  $this->db->where($this->id, $id);
  $this->db->update($this->table, $data);
 }

 // update data
 public function updateStok($id, $data)
 {
  $this->db->where($this->id, $id);
  $this->db->update($this->table, $data);
 }

 // delete data
 public function delete($id)
 {
  $this->db->where($this->id, $id);
  $this->db->delete($this->table);
 }

}

/* End of file Tab_barang_model.php */
/* Location: ./application/models/Tab_barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-04 02:52:02 */
/* http://harviacode.com */
